# Generated by Django 4.0.3 on 2022-03-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
