# Generated by Django 4.0.3 on 2022-03-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
