# Generated by Django 4.0.3 on 2022-03-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_review_review_on_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=256)),
                ('detail', models.TextField(max_length=2048)),
                ('preview', models.FileField(upload_to='uploads/stock/')),
                ('license', models.FileField(upload_to='uploads/license/')),
                ('download', models.FileField(upload_to='uploads/item/')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('catrgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
