# Generated by Django 4.0.3 on 2022-03-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='catrgory',
            new_name='category',
        ),
    ]
